### ISSUE TITLE
How to add R packages

### ISSUE THREAD

**Issue by marounbs** [auwerxlab/renku-r-template#1]
Hi @alexisrapin,
It's not clear to me how one can add R packages to this template - especially with the renv. Can you explain please? Maybe best to put relevant instructions in the README.md.

Thanks!

**Comment by alexisrapin** [comment]
Thank you @marounbs !

The preferred solution would be:
1. Use ``install.packages()`` within an R session to install desired packages.
2. Then, register the new packages in the ``renv.lock`` file using ``renv::snapshot()``.
3. Finally, commit/push the changes so that the package remain available the next time an interactive environment is run.

There are alternatives, such as editing the ``renv.lock`` file directly (if you know what you are doing) or using ``install.R``. \
Using ``install.R`` wont automatically register the new packages in the ``renv.lock`` file though.

These instructions are now included in the README.md, as per release v1.0.1.
